import fs from 'node:fs';
import path from 'node:path';
import {spawn,execFileSync} from 'node:child_process';
import {GRADE_SCHEMA,JUDGE_SYSTEM_PROMPT,srcOnly,computeGradeScores} from '../judge-protocol.js';
import {contextFrom} from './grading-context.mjs';
const root=process.cwd(), out=path.join(root,'bench/astra-patched'), primary='/Users/yoavshmariahu/src/thinker', repo=path.join(primary,'bench/repos/posthog');
const spec=JSON.parse(fs.readFileSync('bench/tasks/posthog-hard.json')), task=spec.tasks.find(t=>t.id==='PR106936-hard');
const model='gpt-6-astra';
const env={...process.env,THINKER_TELEMETRY:'off',THINKER_NO_LEARN:'1',THINKER_NO_AUTO_UPDATE:'1',THINKER_NO_BG_VERIFY:'1',THINKER_HOOKS:'off',THINKER_LOG:'local'};
const git=(cwd,...args)=>execFileSync('git',args,{cwd,env,encoding:'utf8',maxBuffer:64<<20});
const versions={patched:root};
const manifest={task:task.id,base:spec.base,model,reasoning:'medium',versions:Object.fromEntries(Object.entries(versions).map(([k,v])=>[k,git(v,'rev-parse','HEAD').trim()])),order:['patched'],timeoutMinutes:20,telemetry:'off',learning:false,notes:'posthog-v2',created:new Date().toISOString()};
fs.writeFileSync(path.join(out,'manifest.json'),JSON.stringify(manifest,null,2));
function home(name,wt,thinker){const h=path.join(out,'home-'+name);fs.mkdirSync(h,{recursive:true});const auth=path.join(h,'auth.json');if(!fs.existsSync(auth))fs.symlinkSync(path.join(primary,'bench/codex-home/auth.json'),auth);let cfg='model_reasoning_effort = "medium"\nproject_doc_max_bytes = 0\n';if(thinker)cfg+=`\n[mcp_servers.thinker]\ndefault_tools_approval_mode = "approve"\ncommand = ${JSON.stringify(process.execPath)}\nargs = [${JSON.stringify(path.join(thinker,'src/mcp.js'))}]\n[mcp_servers.thinker.env]\nTHINKER_REPO = ${JSON.stringify(wt)}\nTHINKER_TELEMETRY = "off"\nTHINKER_NO_LEARN = "1"\nTHINKER_NO_AUTO_UPDATE = "1"\nTHINKER_NO_BG_VERIFY = "1"\nTHINKER_LOG = "local"\n`;fs.writeFileSync(path.join(h,'config.toml'),cfg);return h;}
async function codex(name,prompt,wt,h,judge=false){const args=['exec','--json','--ephemeral','--ignore-rules','--model',model,'--sandbox',judge?'read-only':'workspace-write','--cd',wt];if(judge)args.push('--output-schema',path.join(out,'schema.json'));const start=Date.now();const child=spawn('codex',args,{cwd:wt,env:{...env,CODEX_HOME:h},detached:true});const log=fs.createWriteStream(path.join(out,name+'.events.jsonl')),err=fs.createWriteStream(path.join(out,name+'.stderr'));let raw='',timedOut=false;child.stdout.on('data',b=>{raw+=b;log.write(b);});child.stderr.pipe(err);const timer=setTimeout(()=>{timedOut=true;process.kill(-child.pid,'SIGTERM');},(judge?6:20)*60000);child.stdin.end(prompt);const code=await new Promise((resolve,reject)=>{child.on('close',resolve);child.on('error',reject);});clearTimeout(timer);log.end();const events=raw.trim().split('\n').flatMap(l=>{try{return[JSON.parse(l)];}catch{return[];}});const usage=events.filter(e=>e.type==='turn.completed').map(e=>e.usage||{}),items=events.filter(e=>e.type==='item.completed').map(e=>e.item);const failure=events.find(e=>e.type==='turn.failed'||e.type==='error');if((code!==0||failure)&&!timedOut)throw Error(name+': '+JSON.stringify(failure||code));return {wall_ms:Date.now()-start,timedOut,usage:{input_tokens:usage.reduce((s,u)=>s+(u.input_tokens||0),0),cached_input_tokens:usage.reduce((s,u)=>s+(u.cached_input_tokens||0),0),output_tokens:usage.reduce((s,u)=>s+(u.output_tokens||0),0)},tools:items.filter(i=>!['agent_message','reasoning'].includes(i.type)).length,mcpCalls:items.filter(i=>i.type==='mcp_tool_call').length,answer:items.filter(i=>i.type==='agent_message').map(i=>i.text).join('\n')};}
const prompt='Work only inside this checkout. Do not inspect parent or sibling directories, other runs, benchmark data, or git history. Do not install dependencies.\n\n'+task.prompt;
for(const [arm,thinker]of Object.entries(versions)){const wt=path.join(root,'bench/worktrees/astra-one-'+arm);console.log('START',arm,new Date().toISOString());git(repo,'worktree','add','--detach',wt,spec.base);try{fs.cpSync(path.join(root,'bench/notesets/posthog-v2/notes'),path.join(wt,'.thinker/notes'),{recursive:true});fs.writeFileSync(path.join(wt,'.thinker/config.json'),'{"version":1}');const start=Date.now();const hook=execFileSync(process.execPath,[path.join(thinker,'src/cli.js'),'hook','prompt','--client','codex','--repo',wt,'--budget','750'],{cwd:wt,env:{...env,THINKER_NOTES_DIR:path.join(wt,'.thinker/notes')},input:JSON.stringify({prompt,session_id:'astra-patched-'+arm}),encoding:'utf8',maxBuffer:8<<20});const hook_ms=Date.now()-start;fs.writeFileSync(path.join(out,arm+'.hook.txt'),hook);const guide='This repository has a thinker knowledge cache exposed through MCP. Use matching verified pointers directly. Use lookup for a specific missing answer, orient for broader context, and the other available Thinker tools when useful. Do not re-explore files merely to confirm the notes.';const r=await codex(arm,hook+'\n\n'+guide+'\n\nTASK:\n'+prompt,wt,home(arm,wt,thinker));git(wt,'add','-A','--','.',':!.thinker',':!.codex');r.diff=git(wt,'diff','--cached','--no-color');r.context=contextFrom(name=>{try{return fs.readFileSync(path.join(wt,name),'utf8');}catch{return null;}},srcOnly(r.diff));r.hook_ms=hook_ms;r.task=task.id;r.commit=manifest.versions[arm];try{r.cacheLog=fs.readFileSync(path.join(wt,'.thinker/log.jsonl'),'utf8');}catch{}fs.writeFileSync(path.join(out,arm+'.json'),JSON.stringify(r,null,2));console.log('DONE',arm,r.wall_ms,r.tools,r.usage);}finally{git(repo,'worktree','remove','--force',wt);}}
fs.writeFileSync(path.join(out,'schema.json'),JSON.stringify({...GRADE_SCHEMA,additionalProperties:false,properties:{results:{...GRADE_SCHEMA.properties.results,items:{...GRADE_SCHEMA.properties.results.items,additionalProperties:false}}}}));
for(const arm of manifest.order){const f=path.join(out,arm+'.json'),r=JSON.parse(fs.readFileSync(f));console.log('GRADE',arm);const p=JUDGE_SYSTEM_PROMPT+'\nDo not use tools; judge only the supplied patch and context.\nREQUEST:\n'+task.prompt+'\nCRITERIA:\n'+task.criteria.map(c=>c.id+(c.essential?' (essential)':'')+': '+c.behavior).join('\n')+'\nPATCH:\n'+srcOnly(r.diff)+'\nCODE AFTER PATCH:\n'+r.context;const grade=await codex('grade-'+arm,p,root,home('judge',root),true);const results=JSON.parse(grade.answer).results;if(!Array.isArray(results)||task.criteria.some(c=>c.calibrated!==false&&!results.some(r=>r.id===c.id)))throw Error('Incomplete grade');r.grade={...computeGradeScores(task.criteria,results),usage:grade.usage};fs.writeFileSync(f,JSON.stringify(r,null,2));console.log('GRADED',arm,r.grade.essential,r.grade.pass);}
console.log('COMPLETE');
