"""Render only measured outcomes from the frozen aggregate."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];OUT=ROOT/'research/astra-mem0-real';s=json.loads((OUT/'raw/summary.json').read_text())
lines=['# Astra: two real coding tasks, matched models','', 'Author: Codex with Yoav Shmariahu. 2026-10-05.','', '**GPT-6 Astra, medium reasoning** was used for exploration, both memory builders and all six coding runs. Same tasks and thinker implementation as the earlier Sonnet experiment; no memory crossed between arms.','', '## Correctness','', '| Task | Arm | Acceptance passed | Acceptance failures/errors | Full-suite passed | Full-suite failures/errors |','|---|---|---:|---:|---:|---:|']
for r in s['rows']:
 a=r['validation']['acceptance'];v=r['validation']['suite']
 lines.append(f"| {r['task']} | {r['arm']} | {a.get('passed','timeout')} | {a.get('failures',0)+a.get('errors',0)} | {v.get('passed','timeout')} | {v.get('failures',0)+v.get('errors',0)} |")
lines+=['','The default-map acceptance set has five tests; capture mode has twelve runnable tests plus one Windows-only skip. Full suites also contain platform/optional skips. Passing these tests does not establish untested behavior.','', '## Tokens and time','', '| Both tasks | No memory | thinker | Mem0 OSS |','|---|---:|---:|---:|']
t=s['totals'];arms=['control','thinker','mem0']
for label,key in [('Acceptance tasks passed','acceptance_tasks_passed'),('Full suites passed','full_suites_passed'),('Solver tokens','solver_tokens'),('Memory-build tokens','build_tokens'),('Build + solve tokens','build_solve_tokens'),('Tool events','tool_calls')]:lines.append('| '+label+' | '+' | '.join(f'{t[a][key]:,}'+('/2' if key.endswith('passed') else '') for a in arms)+' |')
lines.append('| Solver seconds | '+' | '.join(f"{t[a]['solver_wall_ms']/1000:.1f}" for a in arms)+' |')
lines.append('| Build + retrieval + solver seconds | '+' | '.join(f"{sum(t[a][k] for k in ['solver_wall_ms','build_wall_ms','retrieval_wall_ms'])/1000:.1f}" for a in arms)+' |')
lines+=['','Input tokens already include cached input. Totals add input and output only. These counters are not financial costs.','', '| Task | Arm | Solver tokens | Solver seconds | Build tokens |','|---|---|---:|---:|---:|']
for r in s['rows']:lines.append(f"| {r['task']} | {r['arm']} | {r['solver_tokens']:,} | {r['solver_wall_ms']/1000:.1f} | {r['build_tokens']:,} |")
learn=sum(x['tokens'] for x in s['learning']);wall=sum(x['wall_ms'] for x in s['learning'])/1000
lines +=['',f'Generating the shared source sessions cost **{learn:,} tokens and {wall:.1f} seconds**, excluded above. Add that cost to each memory arm when treating the source sessions as setup; it is sunk only when equivalent prior work already exists.','', '## Limits and evidence','', 'One run per arm on two historical public tasks is a pilot, not a general ranking. No selective solver retries. No model judge. Differences from the earlier Sonnet cohort also include the coding harness and regenerated evidence; do not attribute them solely to the model.','', 'See [METHOD.md](METHOD.md) for the pinned commits, environment, model controls, baseline pager-test caveat, isolation limits and reproduction steps. [raw/summary.json](raw/summary.json) retains detailed counters; `raw-evidence.tar.gz` retains prompts, full events, patches, memory outputs, upstream gold fixtures and test logs.','']
text='\n'.join(lines)
if all(t[a]['acceptance_tasks_passed']==2 for a in arms):
 text=text.replace('## Correctness', 'All three arms passed both task-specific acceptance sets. Neither memory arm demonstrated a correctness advantage on this sample. No memory used the fewest build-plus-solve tokens; thinker used 19% more and Mem0 48% more. Thinker helped on the smaller task but spent more on the capture task.\n\n## Correctness',1)
if (OUT/'raw/pager-diagnostic.json').exists():
 text=text.replace('## Tokens and time', "The original thinker full-suite run had one failure: `test_echo_via_pager[test5- cat ]`, outside the task's acceptance tests. It expects a pager subprocess not to write before a generator raises—a timing-sensitive assumption. The solver patch changes `src/click/testing.py`, not the pager implementation or `tests/test_utils.py`.\n\nA balanced diagnostic ran the generator-exception pager cases ten times each on all three solver patches, the upstream reference fix, and the original base, in rotating order. Every solver arm and the base passed all ten diagnostic runs; the upstream reference failed once (`test5-cat`). Together with the base preflight's pager failure, this supports a pre-existing timing flake rather than evidence of a thinker-specific regression. The original **1/2 full-suite score remains unchanged**; no solver was rerun. See [raw/pager-diagnostic.json](raw/pager-diagnostic.json).\n\n## Tokens and time",1)
(OUT/'README.md').write_text(text)
