// Desired behaviors of the system: notes of kind `behavior`. A person writes one (or accepts one an
// agent proposed), and from then on the code must conform to it, never the other way round:
// verification (ops.js:verifyBehavior) answers holds / broken / moved and never retires or rewrites
// it, a review (review.js:assessBehavior) reports code that stops upholding it as a violation, the
// commit-time repair hook leaves it alone, archiving never takes it, and distillation never writes
// one. `mutability` is `fixed` (never revised; a violation is an error) or `mutable` (revised only
// by a change that edits the note itself). `thinker system` is the view of them, and `.thinker/SYSTEM.md`
// the same for people reading the repository without the tool.
import fs from 'node:fs';
import path from 'node:path';
import { createNote, refresh, MUTABILITY } from './ops.js';

export const isBehavior = n => n?.kind === 'behavior';
// A behavior from a person, a pull request or a document stands; one an agent saved (remember) is a
// proposal until `thinker system accept` makes it a person's.
export const proposed = n => !['human', 'pr', 'doc'].includes(n?.source?.type);
// holds / violated / unverified (its enforcement changed and no verification has looked yet) / retired
export function behaviorState(n) {
  if (n.status === 'invalid') return 'retired';
  if (n.status === 'violated') return 'violated';
  if (n.status === 'stale') return 'unverified';
  return 'holds';
}

// Every behavior, re-hashed against the working tree, the broken ones first.
const ORDER = { violated: 0, unverified: 1, holds: 2, retired: 3 };
export function listBehaviors(store, { all = false } = {}) {
  const notes = refresh(store, store.list().filter(isBehavior));
  return notes.filter(n => all || n.status !== 'invalid')
    .map(n => ({ note: n, id: n.id, title: n.title, mutability: n.mutability || 'mutable', state: behaviorState(n), proposed: proposed(n), shared: store.isShared(n.id), revised: n.revised ? { at: n.revised.at, commit: String(n.revised.commit || '').slice(0, 10), reason: n.revised.reason || '' } : null, since: n.violated?.commit ? String(n.violated.commit).slice(0, 10) : '', reason: n.violated?.reason || (n.stale?.changed || []).map(c => `${c.path}${c.symbol ? ':' + c.symbol : ''} (${c.reason})`).join(', ') }))
    .sort((a, b) => ORDER[a.state] - ORDER[b.state] || Number(a.mutability === 'mutable') - Number(b.mutability === 'mutable') || a.title.localeCompare(b.title));
}

export function renderBehaviors(rows) {
  if (!rows.length) return 'No desired behaviors yet. Write one with `thinker system add`, or promote a note that already states a rule: `thinker system propose`.';
  const L = [];
  for (const r of rows) {
    const flags = [r.mutability, r.proposed ? 'proposed' : '', r.shared ? '' : 'local', r.revised ? `revised ${String(r.revised.at).slice(0, 10)} to match ${r.revised.commit}` : ''].filter(Boolean).join(', ');
    L.push(`${r.state.padEnd(10)} [${flags}] ${r.title}  (id: ${r.id})${r.state === 'violated' ? `\n           since ${r.since || '?'}: ${r.reason}` : r.state === 'unverified' ? `\n           changed: ${r.reason}` : ''}`);
  }
  const broken = rows.filter(r => r.state === 'violated').length, unv = rows.filter(r => r.state === 'unverified').length;
  L.push(`${rows.length} desired behavior${rows.length === 1 ? '' : 's'}${broken ? `, ${broken} not upheld by the code` : ''}${unv ? `, ${unv} unverified (thinker verify)` : ''}${rows.some(r => r.proposed) ? `, ${rows.filter(r => r.proposed).length} proposed by agents (thinker system accept <id>)` : ''}`);
  return L.join('\n');
}

// `.thinker/SYSTEM.md`: the behaviors as a document in the repository, for people and tools that do
// not run thinker. Written by `thinker system md`, and again by add, accept and promote when it exists.
export function renderSystemMarkdown(rows, { repoName = '' } = {}) {
  const L = [`# Desired behaviors${repoName ? ` of ${repoName}` : ''}`, '', 'Rules the code must uphold, kept as `behavior` notes in `.thinker/notes/` and checked by `thinker review` and `thinker verify`. A **fixed** behavior is never revised; a **mutable** one is revised only by a change that edits its note. Generated by `thinker system md`; edit the notes, not this file.', ''];
  const section = (title, rs) => { if (!rs.length) return; L.push(`## ${title}`, ''); for (const r of rs) { const n = r.note; L.push(`### ${r.title}`, '', `*${r.mutability}${r.proposed ? ', proposed by an agent' : ''}; id \`${r.id}\`${r.state !== 'holds' ? `; **${r.state}**${r.since ? ` since ${r.since}` : ''}` : ''}${r.revised ? `; revised ${String(r.revised.at).slice(0, 10)} to match commit ${r.revised.commit}` : ''}*`, '', n.body, ''); if (n.applies) L.push(`Applies: ${n.applies}`, ''); L.push(`Upheld at: ${(n.deps || []).map(d => `\`${d.path}${d.symbol ? ':' + d.symbol : ''}\``).join(', ')}`, ''); } };
  section('Fixed', rows.filter(r => r.mutability === 'fixed'));
  section('Mutable', rows.filter(r => r.mutability !== 'fixed'));
  return L.join('\n');
}
export function writeSystemMarkdown(store, { force = false } = {}) {
  const file = path.join(store.dir, 'SYSTEM.md');
  if (!force && !fs.existsSync(file)) return null;
  fs.writeFileSync(file, renderSystemMarkdown(listBehaviors(store), { repoName: path.basename(store.repo) }) + '\n');
  return file;
}

// A person writes a behavior: like `thinker add`, with the kind and mutability set.
export function addBehavior(store, input, { mutability, source = { type: 'human' } } = {}) {
  const m = mutability || input.mutability;
  if (m && !MUTABILITY.includes(m)) return { error: `mutability must be one of ${MUTABILITY.join(', ')}` };
  const r = createNote(store, { ...input, kind: 'behavior', mutability: m || 'mutable' }, { source });
  if (!r.error) writeSystemMarkdown(store);
  return r;
}

// A rule note becomes a behavior; the
// person who promotes it is its source from then on, and the original kind is kept in `promoted`.
export function promoteBehavior(store, id, { mutability = 'mutable' } = {}) {
  const n = store.get(id);
  if (!n) return { error: 'no such note' };
  if (!MUTABILITY.includes(mutability)) return { error: `mutability must be one of ${MUTABILITY.join(', ')}` };
  if (isBehavior(n) && !proposed(n)) { if (n.mutability === mutability) return { note: n, unchanged: true }; }
  const next = { ...n, kind: 'behavior', mutability, source: { type: 'human', promoted: isBehavior(n) ? n.source?.type || 'agent' : n.kind, from: n.source }, confidence: Math.max(n.confidence ?? 0.7, 0.8) };
  if (next.status === 'invalid') { next.status = 'fresh'; delete next.invalidReason; }
  delete next.archived;
  store.put(next);
  store.log({ op: 'behavior', id, action: isBehavior(n) ? 'accept' : 'promote', from: isBehavior(n) ? undefined : n.kind, mutability });
  writeSystemMarkdown(store);
  return { note: next };
}
export const acceptBehavior = (store, id, opts) => promoteBehavior(store, id, opts);

// Candidates for promotion: the notes that state rules, the ones the sessions acted on most first.
export function proposeBehaviors(store, { kinds = ['rule'], limit = 20 } = {}) {
  return store.list().filter(n => kinds.includes(n.kind) && n.status !== 'invalid')
    .map(n => ({ id: n.id, title: n.title, kind: n.kind, confidence: n.confidence ?? 0.7, confirmed: n.attest?.confirmed || 0, uses: n.uses || 0, source: n.source?.type || 'agent' }))
    .sort((a, b) => b.confirmed - a.confirmed || b.uses - a.uses || b.confidence - a.confidence).slice(0, limit);
}

// What the MCP lookup returns for the kind as a whole: the list, each with its state, before the bodies.
export function behaviorsSummary(rows) {
  return rows.map(r => `- ${r.state}${r.state === 'violated' ? ` (since ${r.since || '?'})` : ''} [${r.mutability}${r.proposed ? ', proposed' : ''}] ${r.title}  (id: ${r.id})`).join('\n');
}
